"""Per-code adapter specs for the thermal-transport DAG.

Each submodule holds the StateAdapterSpec and OperationAdapterSpec instances
for one code (kaldo, phono3py, ...). All instances are constructed against
the shared operator DAG in `omai.thermal_transport.operator`, so cross-code
agreement is checked at the operator level (per Principle 7).

Re-exports the per-code spec instances for convenience; the canonical
location is the corresponding submodule (e.g.
`omai.thermal_transport.representation.kaldo`).
"""

from omai.thermal_transport.representation.kaldo import (
    KALDO_COMPUTE_FORCE_CONSTANTS_2,
    KALDO_COMPUTE_FORCE_CONSTANTS_3,
    KALDO_COMPUTE_HEAT_CAPACITY,
    KALDO_COMPUTE_LINEWIDTH,
    KALDO_FREQUENCY,
    KALDO_GROUP_VELOCITY,
    KALDO_HEAT_CAPACITY,
    KALDO_LINEWIDTH,
    KALDO_SOLVE_BTE_DIRECT,
    KALDO_THERMAL_CONDUCTIVITY_DIRECT,
    KALDO_THERMAL_CONDUCTIVITY_RTA,
    kaldo_compute_linewidth_spec,
)
from omai.thermal_transport.representation.phono3py import (
    PHONO3PY_COMPUTE_FORCE_CONSTANTS_2,
    PHONO3PY_COMPUTE_FORCE_CONSTANTS_3,
    PHONO3PY_COMPUTE_HEAT_CAPACITY,
    PHONO3PY_COMPUTE_LINEWIDTH,
    PHONO3PY_FREQUENCY,
    PHONO3PY_GROUP_VELOCITY,
    PHONO3PY_HEAT_CAPACITY,
    PHONO3PY_LINEWIDTH,
    PHONO3PY_SOLVE_BTE_DIRECT,
    PHONO3PY_THERMAL_CONDUCTIVITY_DIRECT,
    PHONO3PY_THERMAL_CONDUCTIVITY_RTA,
)
from omai.thermal_transport.representation.phonopy import (
    PHONOPY_FREQUENCY,
    PHONOPY_MOLAR_HEAT_CAPACITY,
)
from omai.thermal_transport.representation.shengbte import (
    SHENGBTE_COMPUTE_FORCE_CONSTANTS_2,
    SHENGBTE_COMPUTE_FORCE_CONSTANTS_3,
    SHENGBTE_COMPUTE_LINEWIDTH,
    SHENGBTE_FREQUENCY,
    SHENGBTE_GROUP_VELOCITY,
    SHENGBTE_LINEWIDTH,
    SHENGBTE_SOLVE_BTE_DIRECT,
    SHENGBTE_THERMAL_CONDUCTIVITY_DIRECT,
    SHENGBTE_THERMAL_CONDUCTIVITY_RTA,
    SHENGBTE_VOLUMETRIC_HEAT_CAPACITY,
)

__all__ = [
    "KALDO_COMPUTE_FORCE_CONSTANTS_2",
    "KALDO_COMPUTE_FORCE_CONSTANTS_3",
    "KALDO_COMPUTE_HEAT_CAPACITY",
    "KALDO_COMPUTE_LINEWIDTH",
    "KALDO_FREQUENCY",
    "KALDO_GROUP_VELOCITY",
    "KALDO_HEAT_CAPACITY",
    "KALDO_LINEWIDTH",
    "KALDO_SOLVE_BTE_DIRECT",
    "KALDO_THERMAL_CONDUCTIVITY_DIRECT",
    "KALDO_THERMAL_CONDUCTIVITY_RTA",
    "kaldo_compute_linewidth_spec",
    "PHONO3PY_COMPUTE_FORCE_CONSTANTS_2",
    "PHONO3PY_COMPUTE_FORCE_CONSTANTS_3",
    "PHONO3PY_COMPUTE_HEAT_CAPACITY",
    "PHONO3PY_COMPUTE_LINEWIDTH",
    "PHONO3PY_FREQUENCY",
    "PHONO3PY_GROUP_VELOCITY",
    "PHONO3PY_HEAT_CAPACITY",
    "PHONO3PY_LINEWIDTH",
    "PHONO3PY_SOLVE_BTE_DIRECT",
    "PHONO3PY_THERMAL_CONDUCTIVITY_DIRECT",
    "PHONO3PY_THERMAL_CONDUCTIVITY_RTA",
    "SHENGBTE_COMPUTE_FORCE_CONSTANTS_2",
    "SHENGBTE_COMPUTE_FORCE_CONSTANTS_3",
    "SHENGBTE_COMPUTE_LINEWIDTH",
    "SHENGBTE_FREQUENCY",
    "SHENGBTE_GROUP_VELOCITY",
    "SHENGBTE_LINEWIDTH",
    "SHENGBTE_SOLVE_BTE_DIRECT",
    "SHENGBTE_THERMAL_CONDUCTIVITY_DIRECT",
    "SHENGBTE_THERMAL_CONDUCTIVITY_RTA",
    "SHENGBTE_VOLUMETRIC_HEAT_CAPACITY",
    "PHONOPY_FREQUENCY",
    "PHONOPY_MOLAR_HEAT_CAPACITY",
]
