"""physlib export: the units bridge.

The map stores every value in the SI-scaled canonical unit of its dimension
(omai.representation.units, each Unit's si_scale). physlib models unit systems
as UnitChoices and the conversion factor between two systems as
dimScale : Dimension ->* R>=0.

This module emits a small Lean file anchoring the map's convention against
physlib: our canonical system is SI, so converting a value from our units to
SI is the identity (dimScale SI SI d = 1), and conversions between any two unit
systems round-trip (dimScale is transitive). These are the load-bearing facts
that make "the map's values live in a definite unit system, provably" true.

Scope is honest: physlib's dimScale is noncomputable and its UnitChoices has
five bases (no mole), so this is the anchor, not a proof of every numeric
conversion factor. The per-unit si_scale values remain the Python source of
truth for actual conversion (tested against 29 codes); this file certifies the
algebraic structure they live in.

CLI:  python -m omai.lean_units  ->  writes lean/OpenMaterialsUnits.lean
"""
from __future__ import annotations

from pathlib import Path

_REPO = Path(__file__).resolve().parent.parent


def _version():
    import json
    p = _REPO / "docs" / "data" / "version.json"
    if p.exists():
        try:
            return json.loads(p.read_text()).get("version") or ""
        except Exception:
            return ""
    return ""


def _canonical_units():
    """The map's canonical (si_scale == 1.0) units, for the file's provenance
    note: these are the systems the map's stored values already live in."""
    from omai.representation import units as U
    out = []
    for name, obj in vars(U).items():
        if type(obj).__name__ != "Unit":
            continue
        if getattr(obj, "si_scale", None) == 1.0:
            dim = getattr(getattr(obj, "dimension", None), "name", "")
            out.append((getattr(obj, "name", name), dim))
    return sorted(out)


def build_units():
    ver = _version()[:12] or "unknown"
    canon = _canonical_units()
    note = "\n".join(f"  -- {u} : canonical for {d}" for u, d in canon[:12])
    src = f"""/-
  OpenMaterials: the units bridge to physlib.

  Generated by omai.lean_units from map version {ver}.
  The map stores values in SI-scaled canonical units (each Unit's si_scale in
  omai/representation/units.py). physlib's dimScale is the conversion factor
  between unit systems. These theorems anchor the map's convention: converting
  from our canonical system (SI) to SI is the identity, and conversions between
  any two systems round-trip. Compiles against physlib (Lean 4.31.0).

  A sample of the map's canonical units (si_scale = 1):
{note}

  physlib (leanprover-community/physlib), successor of PhysLean by
  Joseph Tooby-Smith, Apache 2.0.
-/
import Physlib.Units.Basic

namespace OpenMaterials.Units

open Dimension UnitChoices

/-- The map's canonical unit system is SI: a stored value is already in SI
    units, so converting it to SI is the identity for every dimension. -/
theorem canonical_is_identity (d : Dimension) : dimScale SI SI d = 1 :=
  dimScale_self SI d

/-- Conversions compose: a value converted through an intermediate unit system
    equals the direct conversion. Round-trips (u1 -> u2 -> u1) therefore cancel. -/
theorem conversions_compose (u1 u2 u3 : UnitChoices) (d : Dimension) :
    dimScale u1 u2 d * dimScale u2 u3 d = dimScale u1 u3 d :=
  dimScale_transitive u1 u2 u3 d

/-- The trivial dimension (dimensionless) never scales under any unit change. -/
theorem dimensionless_never_scales (u1 u2 : UnitChoices) :
    dimScale u1 u2 1 = 1 :=
  dimScale_one u1 u2

end OpenMaterials.Units
"""
    stats = {"canonical_units": len(canon), "theorems": 3, "map_version": ver}
    return src, stats


def write_units(out: Path | None = None):
    out = out or (_REPO / "lean" / "OpenMaterialsUnits.lean")
    out.parent.mkdir(parents=True, exist_ok=True)
    src, stats = build_units()
    out.write_text(src)
    return out, stats


if __name__ == "__main__":  # pragma: no cover
    path, stats = write_units()
    print(f"wrote {path}")
    for k, v in stats.items():
        print(f"  {k}: {v}")
