/-
  OpenMaterials Tier 2: the executable identities as real-valued theorems.

  Generated by omai.lean_identities from map version f69b18c18fb7.
  A `composition` theorem substitutes an upstream identity into a downstream
  one and proves the chained form equals the flat form (ring / field_simp).
  A `law` theorem states a single identity's formula as a well-typed real
  equation. Dimensional consistency is Tier 1 (OpenMaterials.lean).
  Compiles against Mathlib (Lean 4.31.0).
-/
import Mathlib.Tactic

namespace OpenMaterials.Identities

-- contract_heat_capacity_p_identity (composition)
theorem identity_contract_heat_capacity_p_identity (C_V_mol : ℝ) (K : ℝ) (N_A : ℝ) (T : ℝ) (V_m : ℝ) (V_cell : ℝ) (alpha_V : ℝ) (h_V_m : V_m = (N_A * V_cell)) :
    (C_V_mol + (K * T * V_m * alpha_V ^ 2)) = (C_V_mol + (K * N_A * T * V_cell * alpha_V ^ 2)) := by subst h_V_m; ring

-- contract_zt (composition)
theorem identity_contract_zt (PF : ℝ) (S : ℝ) (T : ℝ) (kappa : ℝ) (kappa_e : ℝ) (kappa_tot : ℝ) (sigma_el : ℝ) (h_PF : PF = (sigma_el * S ^ 2)) (h_kappa_tot : kappa_tot = (kappa + kappa_e)) (hd0 : (kappa + kappa_e) ≠ 0) :
    (PF * T) / (kappa_tot) = (T * sigma_el * S ^ 2) / ((kappa + kappa_e)) := by subst h_PF h_kappa_tot; field_simp

end OpenMaterials.Identities
